### ISSUE TITLE
关于modbusrtu的疑问

### ISSUE THREAD

**Issue by WwYyFan** [Orienfish/ur3-python#1]
@Orienfish 
     你好！我在使用[modbusrtu](https://github.com/Orienfish/ur3-python/blob/master/modbusrtu.c)控制robotiq 2f 抓取东西，当我调用[modbusrtu](https://github.com/Orienfish/ur3-python/blob/master/modbusrtu.c)中的gripper_close来关闭抓手以此来抓住物体时，抓手不会判断是否已经抓住了物体，而是一直关闭抓手直至完全闭合？

**Comment by Orienfish** [comment]
是的，目前这版代码只是单纯闭合，没有检测是否抓到了东西。Manual手册中有可以通过状态gOBJ判断抓取状态（i.e.是否抓到物体），应该是可以做object detection和regrasp的，但我之前并没有尝试。
